/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SessionRouteImport } from './routes/_session'
import { Route as FoundationRouteImport } from './routes/foundation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SessionShellRouteImport } from './routes/_session/_shell'
import { Route as SessionForbiddenRouteImport } from './routes/_session/forbidden'
import { Route as AuthenticatedbookkeepingAccountsRouteImport } from './routes/_authenticated/(bookkeeping)/accounts'
import { Route as AuthenticatedbookkeepingCategoriesRouteImport } from './routes/_authenticated/(bookkeeping)/categories'
import { Route as AuthenticatedbookkeepingTransactionsRouteImport } from './routes/_authenticated/(bookkeeping)/transactions'
import { Route as AuthenticatedcoreIndexRouteImport } from './routes/_authenticated/(core)/index'
import { Route as AuthenticatediamAuditLogsRouteImport } from './routes/_authenticated/(iam)/audit-logs'
import { Route as AuthenticatediamMembersRouteImport } from './routes/_authenticated/(iam)/members'
import { Route as AuthenticatediamMenusRouteImport } from './routes/_authenticated/(iam)/menus'
import { Route as AuthenticatediamRolesRouteImport } from './routes/_authenticated/(iam)/roles'
import { Route as AuthenticatediamSessionsRouteImport } from './routes/_authenticated/(iam)/sessions'
import { Route as SessionShellSystemMenuResetRouteImport } from './routes/_session/_shell/system/menu-reset'
import { Route as AuthenticatedrentalRentalsContractsIndexRouteImport } from './routes/_authenticated/(rental)/rentals/contracts/index'
import { Route as AuthenticatedrentalRentalsContractsContractIdRouteImport } from './routes/_authenticated/(rental)/rentals/contracts/$contractId'
import { Route as AuthenticatedrentalRentalsContractsNewRouteImport } from './routes/_authenticated/(rental)/rentals/contracts/new'
import { Route as AuthenticatedrentalRentalsPropertiesIndexRouteImport } from './routes/_authenticated/(rental)/rentals/properties/index'
import { Route as AuthenticatedrentalRentalsPropertiesPropertyIdRouteImport } from './routes/_authenticated/(rental)/rentals/properties/$propertyId'
import { Route as AuthenticatedrentalRentalsTenantsIndexRouteImport } from './routes/_authenticated/(rental)/rentals/tenants/index'
import { Route as AuthenticatedrentalRentalsTenantsTenantIdRouteImport } from './routes/_authenticated/(rental)/rentals/tenants/$tenantId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/_session',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationRoute = FoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionShellRoute = SessionShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => SessionRoute,
} as any)
const SessionForbiddenRoute = SessionForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => SessionRoute,
} as any)
const AuthenticatedbookkeepingAccountsRoute =
  AuthenticatedbookkeepingAccountsRouteImport.update({
    id: '/(bookkeeping)/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedbookkeepingCategoriesRoute =
  AuthenticatedbookkeepingCategoriesRouteImport.update({
    id: '/(bookkeeping)/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedbookkeepingTransactionsRoute =
  AuthenticatedbookkeepingTransactionsRouteImport.update({
    id: '/(bookkeeping)/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedcoreIndexRoute = AuthenticatedcoreIndexRouteImport.update({
  id: '/(core)/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatediamAuditLogsRoute =
  AuthenticatediamAuditLogsRouteImport.update({
    id: '/(iam)/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatediamMembersRoute = AuthenticatediamMembersRouteImport.update({
  id: '/(iam)/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatediamMenusRoute = AuthenticatediamMenusRouteImport.update({
  id: '/(iam)/menus',
  path: '/menus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatediamRolesRoute = AuthenticatediamRolesRouteImport.update({
  id: '/(iam)/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatediamSessionsRoute =
  AuthenticatediamSessionsRouteImport.update({
    id: '/(iam)/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const SessionShellSystemMenuResetRoute =
  SessionShellSystemMenuResetRouteImport.update({
    id: '/system/menu-reset',
    path: '/system/menu-reset',
    getParentRoute: () => SessionShellRoute,
  } as any)
const AuthenticatedrentalRentalsContractsIndexRoute =
  AuthenticatedrentalRentalsContractsIndexRouteImport.update({
    id: '/(rental)/rentals/contracts/',
    path: '/rentals/contracts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedrentalRentalsContractsContractIdRoute =
  AuthenticatedrentalRentalsContractsContractIdRouteImport.update({
    id: '/(rental)/rentals/contracts/$contractId',
    path: '/rentals/contracts/$contractId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedrentalRentalsContractsNewRoute =
  AuthenticatedrentalRentalsContractsNewRouteImport.update({
    id: '/(rental)/rentals/contracts/new',
    path: '/rentals/contracts/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedrentalRentalsPropertiesIndexRoute =
  AuthenticatedrentalRentalsPropertiesIndexRouteImport.update({
    id: '/(rental)/rentals/properties/',
    path: '/rentals/properties/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedrentalRentalsPropertiesPropertyIdRoute =
  AuthenticatedrentalRentalsPropertiesPropertyIdRouteImport.update({
    id: '/(rental)/rentals/properties/$propertyId',
    path: '/rentals/properties/$propertyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedrentalRentalsTenantsIndexRoute =
  AuthenticatedrentalRentalsTenantsIndexRouteImport.update({
    id: '/(rental)/rentals/tenants/',
    path: '/rentals/tenants/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedrentalRentalsTenantsTenantIdRoute =
  AuthenticatedrentalRentalsTenantsTenantIdRouteImport.update({
    id: '/(rental)/rentals/tenants/$tenantId',
    path: '/rentals/tenants/$tenantId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedcoreIndexRoute
  '/foundation': typeof FoundationRoute
  '/login': typeof LoginRoute
  '/forbidden': typeof SessionForbiddenRoute
  '/accounts': typeof AuthenticatedbookkeepingAccountsRoute
  '/categories': typeof AuthenticatedbookkeepingCategoriesRoute
  '/transactions': typeof AuthenticatedbookkeepingTransactionsRoute
  '/audit-logs': typeof AuthenticatediamAuditLogsRoute
  '/members': typeof AuthenticatediamMembersRoute
  '/menus': typeof AuthenticatediamMenusRoute
  '/roles': typeof AuthenticatediamRolesRoute
  '/sessions': typeof AuthenticatediamSessionsRoute
  '/system/menu-reset': typeof SessionShellSystemMenuResetRoute
  '/rentals/contracts/$contractId': typeof AuthenticatedrentalRentalsContractsContractIdRoute
  '/rentals/contracts/new': typeof AuthenticatedrentalRentalsContractsNewRoute
  '/rentals/properties/$propertyId': typeof AuthenticatedrentalRentalsPropertiesPropertyIdRoute
  '/rentals/tenants/$tenantId': typeof AuthenticatedrentalRentalsTenantsTenantIdRoute
  '/rentals/contracts/': typeof AuthenticatedrentalRentalsContractsIndexRoute
  '/rentals/properties/': typeof AuthenticatedrentalRentalsPropertiesIndexRoute
  '/rentals/tenants/': typeof AuthenticatedrentalRentalsTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedcoreIndexRoute
  '/foundation': typeof FoundationRoute
  '/login': typeof LoginRoute
  '/forbidden': typeof SessionForbiddenRoute
  '/accounts': typeof AuthenticatedbookkeepingAccountsRoute
  '/categories': typeof AuthenticatedbookkeepingCategoriesRoute
  '/transactions': typeof AuthenticatedbookkeepingTransactionsRoute
  '/audit-logs': typeof AuthenticatediamAuditLogsRoute
  '/members': typeof AuthenticatediamMembersRoute
  '/menus': typeof AuthenticatediamMenusRoute
  '/roles': typeof AuthenticatediamRolesRoute
  '/sessions': typeof AuthenticatediamSessionsRoute
  '/system/menu-reset': typeof SessionShellSystemMenuResetRoute
  '/rentals/contracts/$contractId': typeof AuthenticatedrentalRentalsContractsContractIdRoute
  '/rentals/contracts/new': typeof AuthenticatedrentalRentalsContractsNewRoute
  '/rentals/properties/$propertyId': typeof AuthenticatedrentalRentalsPropertiesPropertyIdRoute
  '/rentals/tenants/$tenantId': typeof AuthenticatedrentalRentalsTenantsTenantIdRoute
  '/rentals/contracts': typeof AuthenticatedrentalRentalsContractsIndexRoute
  '/rentals/properties': typeof AuthenticatedrentalRentalsPropertiesIndexRoute
  '/rentals/tenants': typeof AuthenticatedrentalRentalsTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_session': typeof SessionRouteWithChildren
  '/foundation': typeof FoundationRoute
  '/login': typeof LoginRoute
  '/_session/_shell': typeof SessionShellRouteWithChildren
  '/_session/forbidden': typeof SessionForbiddenRoute
  '/_authenticated/(bookkeeping)/accounts': typeof AuthenticatedbookkeepingAccountsRoute
  '/_authenticated/(bookkeeping)/categories': typeof AuthenticatedbookkeepingCategoriesRoute
  '/_authenticated/(bookkeeping)/transactions': typeof AuthenticatedbookkeepingTransactionsRoute
  '/_authenticated/(iam)/audit-logs': typeof AuthenticatediamAuditLogsRoute
  '/_authenticated/(iam)/members': typeof AuthenticatediamMembersRoute
  '/_authenticated/(iam)/menus': typeof AuthenticatediamMenusRoute
  '/_authenticated/(iam)/roles': typeof AuthenticatediamRolesRoute
  '/_authenticated/(iam)/sessions': typeof AuthenticatediamSessionsRoute
  '/_authenticated/(core)/': typeof AuthenticatedcoreIndexRoute
  '/_session/_shell/system/menu-reset': typeof SessionShellSystemMenuResetRoute
  '/_authenticated/(rental)/rentals/contracts/$contractId': typeof AuthenticatedrentalRentalsContractsContractIdRoute
  '/_authenticated/(rental)/rentals/contracts/new': typeof AuthenticatedrentalRentalsContractsNewRoute
  '/_authenticated/(rental)/rentals/properties/$propertyId': typeof AuthenticatedrentalRentalsPropertiesPropertyIdRoute
  '/_authenticated/(rental)/rentals/tenants/$tenantId': typeof AuthenticatedrentalRentalsTenantsTenantIdRoute
  '/_authenticated/(rental)/rentals/contracts/': typeof AuthenticatedrentalRentalsContractsIndexRoute
  '/_authenticated/(rental)/rentals/properties/': typeof AuthenticatedrentalRentalsPropertiesIndexRoute
  '/_authenticated/(rental)/rentals/tenants/': typeof AuthenticatedrentalRentalsTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/foundation'
    | '/login'
    | '/forbidden'
    | '/accounts'
    | '/categories'
    | '/transactions'
    | '/audit-logs'
    | '/members'
    | '/menus'
    | '/roles'
    | '/sessions'
    | '/system/menu-reset'
    | '/rentals/contracts/$contractId'
    | '/rentals/contracts/new'
    | '/rentals/properties/$propertyId'
    | '/rentals/tenants/$tenantId'
    | '/rentals/contracts/'
    | '/rentals/properties/'
    | '/rentals/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/foundation'
    | '/login'
    | '/forbidden'
    | '/accounts'
    | '/categories'
    | '/transactions'
    | '/audit-logs'
    | '/members'
    | '/menus'
    | '/roles'
    | '/sessions'
    | '/system/menu-reset'
    | '/rentals/contracts/$contractId'
    | '/rentals/contracts/new'
    | '/rentals/properties/$propertyId'
    | '/rentals/tenants/$tenantId'
    | '/rentals/contracts'
    | '/rentals/properties'
    | '/rentals/tenants'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_session'
    | '/foundation'
    | '/login'
    | '/_session/_shell'
    | '/_session/forbidden'
    | '/_authenticated/(bookkeeping)/accounts'
    | '/_authenticated/(bookkeeping)/categories'
    | '/_authenticated/(bookkeeping)/transactions'
    | '/_authenticated/(iam)/audit-logs'
    | '/_authenticated/(iam)/members'
    | '/_authenticated/(iam)/menus'
    | '/_authenticated/(iam)/roles'
    | '/_authenticated/(iam)/sessions'
    | '/_authenticated/(core)/'
    | '/_session/_shell/system/menu-reset'
    | '/_authenticated/(rental)/rentals/contracts/$contractId'
    | '/_authenticated/(rental)/rentals/contracts/new'
    | '/_authenticated/(rental)/rentals/properties/$propertyId'
    | '/_authenticated/(rental)/rentals/tenants/$tenantId'
    | '/_authenticated/(rental)/rentals/contracts/'
    | '/_authenticated/(rental)/rentals/properties/'
    | '/_authenticated/(rental)/rentals/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SessionRoute: typeof SessionRouteWithChildren
  FoundationRoute: typeof FoundationRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_session': {
      id: '/_session'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundation': {
      id: '/foundation'
      path: '/foundation'
      fullPath: '/foundation'
      preLoaderRoute: typeof FoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_session/_shell': {
      id: '/_session/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SessionShellRouteImport
      parentRoute: typeof SessionRoute
    }
    '/_session/forbidden': {
      id: '/_session/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof SessionForbiddenRouteImport
      parentRoute: typeof SessionRoute
    }
    '/_authenticated/(bookkeeping)/accounts': {
      id: '/_authenticated/(bookkeeping)/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedbookkeepingAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(bookkeeping)/categories': {
      id: '/_authenticated/(bookkeeping)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedbookkeepingCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(bookkeeping)/transactions': {
      id: '/_authenticated/(bookkeeping)/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedbookkeepingTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(core)/': {
      id: '/_authenticated/(core)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedcoreIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(iam)/audit-logs': {
      id: '/_authenticated/(iam)/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatediamAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(iam)/members': {
      id: '/_authenticated/(iam)/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatediamMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(iam)/menus': {
      id: '/_authenticated/(iam)/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof AuthenticatediamMenusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(iam)/roles': {
      id: '/_authenticated/(iam)/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatediamRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(iam)/sessions': {
      id: '/_authenticated/(iam)/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatediamSessionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_session/_shell/system/menu-reset': {
      id: '/_session/_shell/system/menu-reset'
      path: '/system/menu-reset'
      fullPath: '/system/menu-reset'
      preLoaderRoute: typeof SessionShellSystemMenuResetRouteImport
      parentRoute: typeof SessionShellRoute
    }
    '/_authenticated/(rental)/rentals/contracts/': {
      id: '/_authenticated/(rental)/rentals/contracts/'
      path: '/rentals/contracts'
      fullPath: '/rentals/contracts/'
      preLoaderRoute: typeof AuthenticatedrentalRentalsContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(rental)/rentals/contracts/$contractId': {
      id: '/_authenticated/(rental)/rentals/contracts/$contractId'
      path: '/rentals/contracts/$contractId'
      fullPath: '/rentals/contracts/$contractId'
      preLoaderRoute: typeof AuthenticatedrentalRentalsContractsContractIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(rental)/rentals/contracts/new': {
      id: '/_authenticated/(rental)/rentals/contracts/new'
      path: '/rentals/contracts/new'
      fullPath: '/rentals/contracts/new'
      preLoaderRoute: typeof AuthenticatedrentalRentalsContractsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(rental)/rentals/properties/': {
      id: '/_authenticated/(rental)/rentals/properties/'
      path: '/rentals/properties'
      fullPath: '/rentals/properties/'
      preLoaderRoute: typeof AuthenticatedrentalRentalsPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(rental)/rentals/properties/$propertyId': {
      id: '/_authenticated/(rental)/rentals/properties/$propertyId'
      path: '/rentals/properties/$propertyId'
      fullPath: '/rentals/properties/$propertyId'
      preLoaderRoute: typeof AuthenticatedrentalRentalsPropertiesPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(rental)/rentals/tenants/': {
      id: '/_authenticated/(rental)/rentals/tenants/'
      path: '/rentals/tenants'
      fullPath: '/rentals/tenants/'
      preLoaderRoute: typeof AuthenticatedrentalRentalsTenantsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(rental)/rentals/tenants/$tenantId': {
      id: '/_authenticated/(rental)/rentals/tenants/$tenantId'
      path: '/rentals/tenants/$tenantId'
      fullPath: '/rentals/tenants/$tenantId'
      preLoaderRoute: typeof AuthenticatedrentalRentalsTenantsTenantIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedbookkeepingAccountsRoute: typeof AuthenticatedbookkeepingAccountsRoute
  AuthenticatedbookkeepingCategoriesRoute: typeof AuthenticatedbookkeepingCategoriesRoute
  AuthenticatedbookkeepingTransactionsRoute: typeof AuthenticatedbookkeepingTransactionsRoute
  AuthenticatediamAuditLogsRoute: typeof AuthenticatediamAuditLogsRoute
  AuthenticatediamMembersRoute: typeof AuthenticatediamMembersRoute
  AuthenticatediamMenusRoute: typeof AuthenticatediamMenusRoute
  AuthenticatediamRolesRoute: typeof AuthenticatediamRolesRoute
  AuthenticatediamSessionsRoute: typeof AuthenticatediamSessionsRoute
  AuthenticatedcoreIndexRoute: typeof AuthenticatedcoreIndexRoute
  AuthenticatedrentalRentalsContractsContractIdRoute: typeof AuthenticatedrentalRentalsContractsContractIdRoute
  AuthenticatedrentalRentalsContractsNewRoute: typeof AuthenticatedrentalRentalsContractsNewRoute
  AuthenticatedrentalRentalsPropertiesPropertyIdRoute: typeof AuthenticatedrentalRentalsPropertiesPropertyIdRoute
  AuthenticatedrentalRentalsTenantsTenantIdRoute: typeof AuthenticatedrentalRentalsTenantsTenantIdRoute
  AuthenticatedrentalRentalsContractsIndexRoute: typeof AuthenticatedrentalRentalsContractsIndexRoute
  AuthenticatedrentalRentalsPropertiesIndexRoute: typeof AuthenticatedrentalRentalsPropertiesIndexRoute
  AuthenticatedrentalRentalsTenantsIndexRoute: typeof AuthenticatedrentalRentalsTenantsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedbookkeepingAccountsRoute: AuthenticatedbookkeepingAccountsRoute,
  AuthenticatedbookkeepingCategoriesRoute:
    AuthenticatedbookkeepingCategoriesRoute,
  AuthenticatedbookkeepingTransactionsRoute:
    AuthenticatedbookkeepingTransactionsRoute,
  AuthenticatediamAuditLogsRoute: AuthenticatediamAuditLogsRoute,
  AuthenticatediamMembersRoute: AuthenticatediamMembersRoute,
  AuthenticatediamMenusRoute: AuthenticatediamMenusRoute,
  AuthenticatediamRolesRoute: AuthenticatediamRolesRoute,
  AuthenticatediamSessionsRoute: AuthenticatediamSessionsRoute,
  AuthenticatedcoreIndexRoute: AuthenticatedcoreIndexRoute,
  AuthenticatedrentalRentalsContractsContractIdRoute:
    AuthenticatedrentalRentalsContractsContractIdRoute,
  AuthenticatedrentalRentalsContractsNewRoute:
    AuthenticatedrentalRentalsContractsNewRoute,
  AuthenticatedrentalRentalsPropertiesPropertyIdRoute:
    AuthenticatedrentalRentalsPropertiesPropertyIdRoute,
  AuthenticatedrentalRentalsTenantsTenantIdRoute:
    AuthenticatedrentalRentalsTenantsTenantIdRoute,
  AuthenticatedrentalRentalsContractsIndexRoute:
    AuthenticatedrentalRentalsContractsIndexRoute,
  AuthenticatedrentalRentalsPropertiesIndexRoute:
    AuthenticatedrentalRentalsPropertiesIndexRoute,
  AuthenticatedrentalRentalsTenantsIndexRoute:
    AuthenticatedrentalRentalsTenantsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SessionShellRouteChildren {
  SessionShellSystemMenuResetRoute: typeof SessionShellSystemMenuResetRoute
}

const SessionShellRouteChildren: SessionShellRouteChildren = {
  SessionShellSystemMenuResetRoute: SessionShellSystemMenuResetRoute,
}

const SessionShellRouteWithChildren = SessionShellRoute._addFileChildren(
  SessionShellRouteChildren,
)

interface SessionRouteChildren {
  SessionShellRoute: typeof SessionShellRouteWithChildren
  SessionForbiddenRoute: typeof SessionForbiddenRoute
}

const SessionRouteChildren: SessionRouteChildren = {
  SessionShellRoute: SessionShellRouteWithChildren,
  SessionForbiddenRoute: SessionForbiddenRoute,
}

const SessionRouteWithChildren =
  SessionRoute._addFileChildren(SessionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SessionRoute: SessionRouteWithChildren,
  FoundationRoute: FoundationRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
