services:
  db-prepare:
    environment:
      NODE_ENV: development
      DATABASE_URL: ${COMPOSE_DATABASE_URL:?COMPOSE_DATABASE_URL is required}
    volumes:
      - ../../apps/server/src:/app/apps/server/src
      - ../../packages/shared/src:/app/packages/shared/src

  server:
    command: pnpm --filter @xpense/server dev
    environment:
      NODE_ENV: development
      DATABASE_URL: ${COMPOSE_DATABASE_URL:?COMPOSE_DATABASE_URL is required}
    volumes:
      - ../../apps/server/src:/app/apps/server/src
      - ../../packages/shared/src:/app/packages/shared/src

  web:
    command: pnpm --filter @xpense/web dev
    environment:
      NODE_ENV: development
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:?VITE_API_BASE_URL is required}
    volumes:
      - ../../apps/web/src:/app/apps/web/src
      - ../../apps/web/index.html:/app/apps/web/index.html
      - ../../apps/web/vite.config.ts:/app/apps/web/vite.config.ts
      - ../../packages/shared/src:/app/packages/shared/src
