import type { MenuTemplateNode } from "./menu-template.js";

/** 账单页面与独立财务操作，沿用租赁目录。 */
export const BILLING_MENU_TEMPLATE: readonly MenuTemplateNode[] = [
  {
    templateKey: "rental-bills",
    parentTemplateKey: "rental",
    type: "menu",
    name: "租赁账单",
    routeKey: "RentalBills",
    icon: "ReceiptText",
    permissionCode: "rental_bills:read",
    isExternal: false,
    isVisible: true,
    keepAlive: true,
    sortOrder: 30,
  },
  {
    templateKey: "rental-bill-detail",
    parentTemplateKey: "rental-bills",
    type: "menu",
    name: "账单详情",
    routeKey: "RentalBillDetail",
    icon: null,
    permissionCode: "rental_bills:read",
    isExternal: false,
    isVisible: false,
    keepAlive: false,
    sortOrder: 0,
  },
  {
    templateKey: "rental-settlement",
    parentTemplateKey: "rental-bills",
    type: "menu",
    name: "退租结算",
    routeKey: "RentalSettlement",
    icon: null,
    permissionCode: "rental_settlements:read",
    isExternal: false,
    isVisible: false,
    keepAlive: false,
    sortOrder: 10,
  },
  {
    templateKey: "rental-settlement.confirm",
    parentTemplateKey: "rental-settlement",
    type: "button",
    name: "确认退租结算",
    routeKey: null,
    icon: null,
    permissionCode: "rental_settlements:confirm",
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 100,
  },
  {
    templateKey: "rental-bills.generate",
    parentTemplateKey: "rental-bills",
    type: "button",
    name: "生成账单",
    routeKey: null,
    icon: null,
    permissionCode: "rental_bills:generate",
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 100,
  },
  {
    templateKey: "rental-bills.adjust",
    parentTemplateKey: "rental-bills",
    type: "button",
    name: "调整账单",
    routeKey: null,
    icon: null,
    permissionCode: "rental_bills:adjust",
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 110,
  },
];
