import type { PermissionKey, RouteKey } from "@xpense/shared";

import type { MenuTemplateNode } from "./menu-template.js";

const bookkeepingRouteKeys = {
  accounts: "Accounts",
  categories: "Categories",
  transactions: "Transactions",
} as const satisfies Record<string, RouteKey>;

const bookkeepingPermissionKeys = {
  accountsCreate: "accounts:create",
  accountsDelete: "accounts:delete",
  accountsRead: "accounts:read",
  accountsUpdate: "accounts:update",
  categoriesCreate: "categories:create",
  categoriesDelete: "categories:delete",
  categoriesRead: "categories:read",
  categoriesUpdate: "categories:update",
  transactionsCreate: "transactions:create",
  transactionsDelete: "transactions:delete",
  transactionsRead: "transactions:read",
  transactionsUpdate: "transactions:update",
} as const satisfies Record<string, PermissionKey>;

/** 新组织与菜单重置流程复用的记账菜单模板。 */
export const BOOKKEEPING_MENU_TEMPLATE: readonly MenuTemplateNode[] = [
  {
    templateKey: "bookkeeping",
    parentTemplateKey: null,
    type: "directory",
    name: "记账管理",
    routeKey: null,
    icon: "ReceiptText",
    permissionCode: null,
    isExternal: null,
    isVisible: true,
    keepAlive: null,
    sortOrder: 5,
  },
  {
    templateKey: "transactions",
    parentTemplateKey: "bookkeeping",
    type: "menu",
    name: "交易记录",
    routeKey: bookkeepingRouteKeys.transactions,
    icon: "ReceiptText",
    permissionCode: bookkeepingPermissionKeys.transactionsRead,
    isExternal: false,
    isVisible: true,
    keepAlive: true,
    sortOrder: 0,
  },
  {
    templateKey: "transactions.create",
    parentTemplateKey: "transactions",
    type: "button",
    name: "新增交易",
    routeKey: null,
    icon: null,
    permissionCode: bookkeepingPermissionKeys.transactionsCreate,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 100,
  },
  {
    templateKey: "transactions.update",
    parentTemplateKey: "transactions",
    type: "button",
    name: "编辑交易",
    routeKey: null,
    icon: null,
    permissionCode: bookkeepingPermissionKeys.transactionsUpdate,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 110,
  },
  {
    templateKey: "transactions.delete",
    parentTemplateKey: "transactions",
    type: "button",
    name: "删除交易",
    routeKey: null,
    icon: null,
    permissionCode: bookkeepingPermissionKeys.transactionsDelete,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 120,
  },
  {
    templateKey: "accounts",
    parentTemplateKey: "bookkeeping",
    type: "menu",
    name: "账户管理",
    routeKey: bookkeepingRouteKeys.accounts,
    icon: "WalletCards",
    permissionCode: bookkeepingPermissionKeys.accountsRead,
    isExternal: false,
    isVisible: true,
    keepAlive: true,
    sortOrder: 10,
  },
  {
    templateKey: "accounts.create",
    parentTemplateKey: "accounts",
    type: "button",
    name: "新增账户",
    routeKey: null,
    icon: null,
    permissionCode: bookkeepingPermissionKeys.accountsCreate,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 100,
  },
  {
    templateKey: "accounts.update",
    parentTemplateKey: "accounts",
    type: "button",
    name: "编辑账户",
    routeKey: null,
    icon: null,
    permissionCode: bookkeepingPermissionKeys.accountsUpdate,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 110,
  },
  {
    templateKey: "accounts.delete",
    parentTemplateKey: "accounts",
    type: "button",
    name: "删除账户",
    routeKey: null,
    icon: null,
    permissionCode: bookkeepingPermissionKeys.accountsDelete,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 120,
  },
  {
    templateKey: "categories",
    parentTemplateKey: "bookkeeping",
    type: "menu",
    name: "分类管理",
    routeKey: bookkeepingRouteKeys.categories,
    icon: "Shapes",
    permissionCode: bookkeepingPermissionKeys.categoriesRead,
    isExternal: false,
    isVisible: true,
    keepAlive: true,
    sortOrder: 20,
  },
  {
    templateKey: "categories.create",
    parentTemplateKey: "categories",
    type: "button",
    name: "新增分类",
    routeKey: null,
    icon: null,
    permissionCode: bookkeepingPermissionKeys.categoriesCreate,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 100,
  },
  {
    templateKey: "categories.update",
    parentTemplateKey: "categories",
    type: "button",
    name: "编辑分类",
    routeKey: null,
    icon: null,
    permissionCode: bookkeepingPermissionKeys.categoriesUpdate,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 110,
  },
  {
    templateKey: "categories.delete",
    parentTemplateKey: "categories",
    type: "button",
    name: "删除分类",
    routeKey: null,
    icon: null,
    permissionCode: bookkeepingPermissionKeys.categoriesDelete,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 120,
  },
];
