import type { PermissionKey, RouteKey } from "@xpense/shared";

import type { MenuTemplateNode } from "./menu-template.js";

const rentalRouteKeys = {
  propertyDetail: "RentalPropertyDetail",
  properties: "RentalProperties",
} as const satisfies Record<string, RouteKey>;

const rentalPermissionKeys = {
  propertiesCreate: "rental_properties:create",
  propertiesDelete: "rental_properties:delete",
  propertiesRead: "rental_properties:read",
  propertiesUpdate: "rental_properties:update",
  spacesCreate: "rental_spaces:create",
  spacesDelete: "rental_spaces:delete",
  spacesUpdate: "rental_spaces:update",
} as const satisfies Record<string, PermissionKey>;

/** 新组织与菜单重置流程复用的租赁菜单模板。 */
export const RENTAL_MENU_TEMPLATE: readonly MenuTemplateNode[] = [
  {
    templateKey: "rental",
    parentTemplateKey: null,
    type: "directory",
    name: "租赁管理",
    routeKey: null,
    icon: "Building2",
    permissionCode: null,
    isExternal: null,
    isVisible: true,
    keepAlive: null,
    sortOrder: 8,
  },
  {
    templateKey: "rental-properties",
    parentTemplateKey: "rental",
    type: "menu",
    name: "房产管理",
    routeKey: rentalRouteKeys.properties,
    icon: "Building2",
    permissionCode: rentalPermissionKeys.propertiesRead,
    isExternal: false,
    isVisible: true,
    keepAlive: true,
    sortOrder: 0,
  },
  {
    templateKey: "rental-property-detail",
    parentTemplateKey: "rental-properties",
    type: "menu",
    name: "房产详情",
    routeKey: rentalRouteKeys.propertyDetail,
    icon: null,
    permissionCode: rentalPermissionKeys.propertiesRead,
    isExternal: false,
    isVisible: false,
    keepAlive: false,
    sortOrder: 0,
  },
  {
    templateKey: "rental-properties.create",
    parentTemplateKey: "rental-properties",
    type: "button",
    name: "新增房产",
    routeKey: null,
    icon: null,
    permissionCode: rentalPermissionKeys.propertiesCreate,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 100,
  },
  {
    templateKey: "rental-properties.update",
    parentTemplateKey: "rental-properties",
    type: "button",
    name: "编辑房产",
    routeKey: null,
    icon: null,
    permissionCode: rentalPermissionKeys.propertiesUpdate,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 110,
  },
  {
    templateKey: "rental-properties.delete",
    parentTemplateKey: "rental-properties",
    type: "button",
    name: "删除房产",
    routeKey: null,
    icon: null,
    permissionCode: rentalPermissionKeys.propertiesDelete,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 120,
  },
  {
    templateKey: "rental-spaces.create",
    parentTemplateKey: "rental-properties",
    type: "button",
    name: "新增空间",
    routeKey: null,
    icon: null,
    permissionCode: rentalPermissionKeys.spacesCreate,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 130,
  },
  {
    templateKey: "rental-spaces.update",
    parentTemplateKey: "rental-properties",
    type: "button",
    name: "编辑空间",
    routeKey: null,
    icon: null,
    permissionCode: rentalPermissionKeys.spacesUpdate,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 140,
  },
  {
    templateKey: "rental-spaces.delete",
    parentTemplateKey: "rental-properties",
    type: "button",
    name: "删除空间",
    routeKey: null,
    icon: null,
    permissionCode: rentalPermissionKeys.spacesDelete,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 150,
  },
];
