import type { PermissionKey, RouteKey } from "@xpense/shared";

import type { MenuTemplateNode } from "./menu-template.js";

const rentalRouteKeys = {
  contractCreate: "RentalContractCreate",
  contractDetail: "RentalContractDetail",
  contracts: "RentalContracts",
  propertyDetail: "RentalPropertyDetail",
  properties: "RentalProperties",
  tenantDetail: "RentalTenantDetail",
  tenants: "RentalTenants",
} as const satisfies Record<string, RouteKey>;

const rentalPermissionKeys = {
  contractsCreate: "rental_contracts:create",
  contractsDelete: "rental_contracts:delete",
  contractsRead: "rental_contracts:read",
  contractsUpdate: "rental_contracts:update",
  propertiesCreate: "rental_properties:create",
  propertiesDelete: "rental_properties:delete",
  propertiesRead: "rental_properties:read",
  propertiesUpdate: "rental_properties:update",
  spacesCreate: "rental_spaces:create",
  spacesDelete: "rental_spaces:delete",
  spacesUpdate: "rental_spaces:update",
  tenantsCreate: "rental_tenants:create",
  tenantsDelete: "rental_tenants:delete",
  tenantsRead: "rental_tenants:read",
  tenantsSensitiveRead: "rental_tenants:sensitive_read",
  tenantsUpdate: "rental_tenants:update",
} as const satisfies Record<string, PermissionKey>;

/** 新组织与菜单重置流程复用的租赁菜单模板。 */
export const RENTAL_MENU_TEMPLATE: readonly MenuTemplateNode[] = [
  {
    templateKey: "rental",
    parentTemplateKey: null,
    type: "directory",
    name: "租赁管理",
    routeKey: null,
    icon: "Building2",
    permissionCode: null,
    isExternal: null,
    isVisible: true,
    keepAlive: null,
    sortOrder: 8,
  },
  {
    templateKey: "rental-properties",
    parentTemplateKey: "rental",
    type: "menu",
    name: "房产管理",
    routeKey: rentalRouteKeys.properties,
    icon: "Building2",
    permissionCode: rentalPermissionKeys.propertiesRead,
    isExternal: false,
    isVisible: true,
    keepAlive: true,
    sortOrder: 0,
  },
  {
    templateKey: "rental-property-detail",
    parentTemplateKey: "rental-properties",
    type: "menu",
    name: "房产详情",
    routeKey: rentalRouteKeys.propertyDetail,
    icon: null,
    permissionCode: rentalPermissionKeys.propertiesRead,
    isExternal: false,
    isVisible: false,
    keepAlive: false,
    sortOrder: 0,
  },
  {
    templateKey: "rental-properties.create",
    parentTemplateKey: "rental-properties",
    type: "button",
    name: "新增房产",
    routeKey: null,
    icon: null,
    permissionCode: rentalPermissionKeys.propertiesCreate,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 100,
  },
  {
    templateKey: "rental-properties.update",
    parentTemplateKey: "rental-properties",
    type: "button",
    name: "编辑房产",
    routeKey: null,
    icon: null,
    permissionCode: rentalPermissionKeys.propertiesUpdate,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 110,
  },
  {
    templateKey: "rental-properties.delete",
    parentTemplateKey: "rental-properties",
    type: "button",
    name: "删除房产",
    routeKey: null,
    icon: null,
    permissionCode: rentalPermissionKeys.propertiesDelete,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 120,
  },
  {
    templateKey: "rental-spaces.create",
    parentTemplateKey: "rental-properties",
    type: "button",
    name: "新增空间",
    routeKey: null,
    icon: null,
    permissionCode: rentalPermissionKeys.spacesCreate,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 130,
  },
  {
    templateKey: "rental-spaces.update",
    parentTemplateKey: "rental-properties",
    type: "button",
    name: "编辑空间",
    routeKey: null,
    icon: null,
    permissionCode: rentalPermissionKeys.spacesUpdate,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 140,
  },
  {
    templateKey: "rental-spaces.delete",
    parentTemplateKey: "rental-properties",
    type: "button",
    name: "删除空间",
    routeKey: null,
    icon: null,
    permissionCode: rentalPermissionKeys.spacesDelete,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 150,
  },
  {
    templateKey: "rental-tenants",
    parentTemplateKey: "rental",
    type: "menu",
    name: "租户管理",
    routeKey: rentalRouteKeys.tenants,
    icon: "Users",
    permissionCode: rentalPermissionKeys.tenantsRead,
    isExternal: false,
    isVisible: true,
    keepAlive: true,
    sortOrder: 10,
  },
  {
    templateKey: "rental-tenant-detail",
    parentTemplateKey: "rental-tenants",
    type: "menu",
    name: "租户详情",
    routeKey: rentalRouteKeys.tenantDetail,
    icon: null,
    permissionCode: rentalPermissionKeys.tenantsRead,
    isExternal: false,
    isVisible: false,
    keepAlive: false,
    sortOrder: 0,
  },
  {
    templateKey: "rental-tenants.create",
    parentTemplateKey: "rental-tenants",
    type: "button",
    name: "新增租户",
    routeKey: null,
    icon: null,
    permissionCode: rentalPermissionKeys.tenantsCreate,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 100,
  },
  {
    templateKey: "rental-tenants.update",
    parentTemplateKey: "rental-tenants",
    type: "button",
    name: "编辑租户",
    routeKey: null,
    icon: null,
    permissionCode: rentalPermissionKeys.tenantsUpdate,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 110,
  },
  {
    templateKey: "rental-tenants.delete",
    parentTemplateKey: "rental-tenants",
    type: "button",
    name: "删除租户",
    routeKey: null,
    icon: null,
    permissionCode: rentalPermissionKeys.tenantsDelete,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 120,
  },
  {
    templateKey: "rental-tenants.sensitive-read",
    parentTemplateKey: "rental-tenants",
    type: "button",
    name: "查看敏感信息",
    routeKey: null,
    icon: null,
    permissionCode: rentalPermissionKeys.tenantsSensitiveRead,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 130,
  },
  {
    templateKey: "rental-contracts",
    parentTemplateKey: "rental",
    type: "menu",
    name: "合同管理",
    routeKey: rentalRouteKeys.contracts,
    icon: "ScrollText",
    permissionCode: rentalPermissionKeys.contractsRead,
    isExternal: false,
    isVisible: true,
    keepAlive: true,
    sortOrder: 20,
  },
  {
    templateKey: "rental-contract-detail",
    parentTemplateKey: "rental-contracts",
    type: "menu",
    name: "合同详情",
    routeKey: rentalRouteKeys.contractDetail,
    icon: null,
    permissionCode: rentalPermissionKeys.contractsRead,
    isExternal: false,
    isVisible: false,
    keepAlive: false,
    sortOrder: 0,
  },
  {
    templateKey: "rental-contracts.create",
    parentTemplateKey: "rental-contracts",
    type: "menu",
    name: "新增合同页面",
    routeKey: rentalRouteKeys.contractCreate,
    icon: null,
    permissionCode: rentalPermissionKeys.contractsCreate,
    isExternal: false,
    isVisible: false,
    keepAlive: false,
    sortOrder: 10,
  },
  {
    templateKey: "rental-contracts.create-action",
    parentTemplateKey: "rental-contracts",
    type: "button",
    name: "新增合同",
    routeKey: null,
    icon: null,
    permissionCode: rentalPermissionKeys.contractsCreate,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 100,
  },
  {
    templateKey: "rental-contracts.update",
    parentTemplateKey: "rental-contracts",
    type: "button",
    name: "编辑合同",
    routeKey: null,
    icon: null,
    permissionCode: rentalPermissionKeys.contractsUpdate,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 110,
  },
  {
    templateKey: "rental-contracts.delete",
    parentTemplateKey: "rental-contracts",
    type: "button",
    name: "删除合同",
    routeKey: null,
    icon: null,
    permissionCode: rentalPermissionKeys.contractsDelete,
    isExternal: null,
    isVisible: null,
    keepAlive: null,
    sortOrder: 120,
  },
];
